// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table etl_logs (Timestamp:datetime, Layer:string, Pipeline:string, Notebook:string, Step:string, Function:string, Message:string, Details:dynamic) 
.create-merge table test_table (row_id:long, random_uniform:real, random_normal:real, random_int:int) 
